from django.contrib import admin
from erasmus_leave.models import *

admin.site.register(Uczelnia)
admin.site.register(Student)
admin.site.register(Wydzial)
admin.site.register(Semestr)
admin.site.register(Przedmiot)
admin.site.register(SzczegolyPraktyk)
admin.site.register(DecyzjaOKwalifikacji)
admin.site.register(DoswiadczenieZawodowe)
admin.site.register(ErazmusWyjazdPraktyka)
admin.site.register(ErazmusWyjazdStudia)
admin.site.register(InstytucjaPrzyjmujaca)
admin.site.register(JezykObcy)
admin.site.register(KierunekSpecjalnosc)
admin.site.register(KompetencjeJezykowe)
admin.site.register(Koordynator)
admin.site.register(Kurs)
admin.site.register(Osoba)
admin.site.register(PlanowaneStudiaZagraniczne)
admin.site.register(PoziomZnajomosciJezyka)
admin.site.register(RokAkademicki)
admin.site.register(WykazZaliczenPrzedmiotow)
admin.site.register(ZmianyWProgramieStudiowaniaZaGranica)
